server:
  port: 8080

dgs:
  graphql:
    path: /graphql
    schema-json:
      path: /schema.json
    schema-locations:
      - classpath*:schema/**/*.graphql*
      - classpath*:graphql-experimental-schemas/**/*.graphql*
    graphiql:
      path: /graphiql
    extensions:
      scalars:
        enabled: true
        numbers:
          enabled: true
        objects:
          enabled: true
        chars:
          enabled: true
        time-dates:
          enabled: true
    introspection:
      enabled: true

logging:
  level:
    com.nhncommerce: debug
    org.springframework: info
    com.netflix.graphql.dgs: info